### PR TITLE
layout edit + translation

### PR DESCRIPTION
**Pull request by crymsc-old**
Changed the layout to match the main course page. Also commented out the "Improve Discussion Page/Forbedre diskusjonssiden" button due to recent Campus updates. Which are disgusting, by the way.

### CODE REVIEW

**Comment by JustTemmie** [comment]
looks gay

**Comment by crymsc-old** [comment]
> looks gay

bro

**Comment by crymsc-old** [comment]
suck woman pp

**Comment by JustTemmie** [comment]
sounds gay

**Comment by crymsc-old** [comment]
merge !!

**Pull request merged**
